vich_uploader:
    db_driver: orm

    mappings:
        avatar:
            uri_prefix: '%path.avatar%'
            upload_destination: '%kernel.project_dir%/public%path.avatar%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        model_thumbnails:
            uri_prefix: '%path.model_thumbnails%'
            upload_destination: '%kernel.project_dir%/public%path.model_thumbnails%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        galery_thumbnails:
            uri_prefix: '%path.galery_thumbnails%'
            upload_destination: '%kernel.project_dir%/public%path.galery_thumbnails%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        attachments:
            uri_prefix: '%path.attachments%'
            upload_destination: '%kernel.project_dir%/public%path.attachments%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer