vich_uploader:
    db_driver: orm

    mappings:
        user_avatar:
            uri_prefix: '%app.path.user.avatar%'
            upload_destination: '%kernel.project_dir%/public%app.path.user.avatar%'
        model:
            uri_prefix: '%app.path.model%'
            upload_destination: '%kernel.project_dir%/public%app.path.model%'
        image:
            uri_prefix: '%app.path.image%'
            upload_destination: '%kernel.project_dir%/public%app.path.image%'
        picture:
            uri_prefix: '%app.path.picture%'
            upload_destination: '%kernel.project_dir%/public%app.path.picture%'
    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
