vich_uploader:
    db_driver: orm

    mappings:
        user_avatar:
            uri_prefix: '%app.path.user.avatar%'
            upload_destination: '%kernel.project_dir%/public%app.path.user.avatar%'

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
