vich_uploader:
    db_driver: orm

    mappings:
        avatar:
            uri_prefix: '%app.path.avatar%'
            upload_destination: '%kernel.project_dir%/public%app.path.avatar%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        model:
            uri_prefix: '%app.path.model%'
            upload_destination: '%kernel.project_dir%/public%app.path.model%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        image:
            uri_prefix: '%app.path.image%'
            upload_destination: '%kernel.project_dir%/public%app.path.image%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        attachments:
            uri_prefix: '%app.path.attachments%'
            upload_destination: '%kernel.project_dir%/public%app.path.attachments%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
