easy_admin:
  entities:
    Comment:
      class: App\Entity\Comment
      label: 'Commentaires'
      form:
        fields:
          - { type: 'group', label: 'Global informations', icon: 'info-circle', columns: 7 }
          - { property: 'message', type: 'textarea' }
          - { property: 'user', type_options: { disabled: true } }
          - { property: 'galery', type_options: { disabled: true } }
          - { property: 'replyTo', type_options: { disabled: true } }
          - { property: 'comments', type_options: { disabled: true } }
          - { type: 'group', label: 'Advanced Settings', columns: 4 }
          - { property: 'isPublished',label: 'Published', help: 'Define if comment is published (visible) or not.' }
          - { property: 'createdAt', type: 'datetime', type_options: { widget: 'single_text', attr: {'class': 'datepicker'}} }
          - { property: 'updatedAt', type: 'datetime', type_options: { widget: 'single_text', attr: {'class': 'datepicker'} } }
      list:
        batch_actions: ['delete']
        actions:
            - { name: 'new', label: '%%entity_label%%', icon: 'plus-circle' }
            - { name: 'edit', label: '', icon: 'edit' }
            - { name: 'delete', label: '', icon: 'trash-alt' }