easy_admin:
  entities:
    Galery:
      class: App\Entity\Galery
      controller: App\Controller\AdminController
      label: 'Galerie'
      form:
        actions:
          - {name: 'createAddPicture', type: 'method', label: 'Créer et ajouter des images'}
        fields:
          - { type: 'group', label: 'Main Informations', columns: 8 }
          - { property: title, columns: md-6 }
          - { property: thumbnailFile, type: 'vich_image', columns: sm-4, css_class: 'preview', type_options: { required: true, allow_delete: false} }
          - { property: 'description', css_class: 'awesome-ckeditor', type: 'textarea' }
          - { property: categories, type_options: { by_reference: false }, columns: 6 }
          - { property: models, type_options: { by_reference: false }, columns: 6 }
          # - { property: 'images', type: 'collection', columns: 6, type_options: { entry_type: 'App\Form\ImageType', by_reference: false }}
          - { property: 'pictureFiles', type: 'App\Form\PictureType', type_options: { multiple: true }}
          #- { property: 'images', type: 'collection', type_options: {mapped: false, attr: {'multiple': 'multiple'}}}
          - { type: 'group', label: 'Advanced Settings', columns: 4 }
          - { property: 'createdAt', type: 'datetime', type_options: { widget: 'single_text', attr: {'class': 'datepicker'}} }
          - { property: 'updatedAt', type: 'datetime', type_options: { widget: 'single_text', attr: {'class': 'datepicker'} } }
          - { type: 'group', label: 'Comments', icon: 'comments'}
          - { property: 'comments', type: embedded_list, type_options: { hidden_fields: { galery: galery, comments: comments, replyTo: replyTo } } }
      edit:
        fields:
            # An image has already been uploaded, image is not required.
            # Image deletion at form level has to be disabled.
            - { property: 'thumbnailFile', type: 'vich_image', type_options: { required: false, allow_delete: false} }
      list:
        batch_actions: ['delete']
        actions:
          - { name: 'new', label: '%%entity_label%%', icon: 'plus-circle' }
          - { name: 'edit', label: '', icon: 'edit' }
          - { name: 'delete', label: '', icon: 'trash-alt' }
        
        fields:
          - id
          - title
          - description
          - { property: 'thumbnail', type: 'image', base_path: '%app.path.image%' }
          - categories
          - models