easy_admin:
  entities:
    Model:
      class: App\Entity\Model
      label: 'Modèle'
      form:
        fields:
          - { type: 'group', label: 'Model Information', columns: 8}
          - { property: name, columns: 6 }
          - { property: 'imageFile', type: 'vich_image', columns: 6 }
          - { property: description, css_class: 'awesome-ckeditor', type: 'textarea' }
          - { property: age, type: integer, columns: 6 }
          - { property: height, columns: 6 }
          - { property: country, columns: 6 }
          - { property: city, columns: 6 }
          - { property: galeries }
          - { type: 'group', label: 'Advanced Settings', columns: 4 }
          - { property: 'createdAt', type: 'datetime', type_options: { widget: 'single_text', attr: {'class': 'datepicker'}} }
          - { property: 'updatedAt', type: 'datetime', type_options: { widget: 'single_text', attr: {'class': 'datepicker'} } }
      list:
        batch_actions: ['delete']
        actions:
            - { name: 'new', label: '%%entity_label%%', icon: 'plus-circle' }
            - { name: 'edit', label: '', icon: 'edit' }
            - { name: 'delete', label: '', icon: 'trash-alt' }