easy_admin:
  site_name: 'deCorban Admin'
  design:
    assets:
      css:
        - '/css/jquery.datetimepicker.css'
      js:
        - '/js/jquery.datetimepicker.full.min.js'
        - '/js/admin.js'